#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run npm run format, add changes and try commit again. 🤢🤮🤢🤮';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤🏀👋😤'
        false;
)

# If everything passes... Now we can commit
#echo '🤔🤔🤔🤔... Alright... Code looks good... Trying to build now. 🤔🤔🤔🤔'
echo '🤔🤔🤔🤔... Alright... Code looks good.'

#npm run build ||
#(
#    echo '❌👷🔨❌ Your build failed ❌👷🔨❌
#    '
#    false;
#)

echo '🤔🤔🤔🤔... Test the code.'
npm run test ||
(
    echo '❌👷🔨❌ Tests failed ❌👷🔨❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You Win!!! 🎉🎉🎉🎉🎉  Committing this now.  ✅✅✅✅'

